### PR TITLE
add GitHub action for push and pr

### PR DESCRIPTION
**Pull request by rizsotto**
Adding continuous integration for this project. (Currently strict checking is disabled.)

### CODE REVIEW

**Comment by rizsotto** [comment]
Hey @inejge , is there a chance for you to look to this PR?

**Comment by inejge** [comment]
Hi, thanks for the PR and sorry for the delay. The crate has been ported to async/await and modernized code-wise; also formatted and passed through Clippy. So, it should a) compile without warnings, b) pass `cargo fmt` tests, c) pass Clippy tests. If you're still interested, could you update the PR to turn on all of those, and also limit Clippy to stable?

**Comment by rizsotto** [comment]
I've updated this PR as you suggested, but still Clippy is still failing.

**Comment by inejge** [comment]
It's probably [this issue](https://github.com/actions-rs/clippy-check/issues/2), so I'm simply going to remove Clippy checking -- I _do_ use Clippy, but can easily live with running it manually from time to time.

**Pull request merged**
